### ISSUE TITLE
Can we use MQ-CPH using SSL ? 

### ISSUE THREAD

**Issue by sm5wzg** [ibm-messaging/mq-cph#1]
Hi, im a new user of MQ-CPH and trying to learn as much as possible of this excellent performance-testing tool. All is working fine and i see that there is a flag for specifying a Cipher spec. My question is where to place the certificate ? is there a parameter to specify this? We are planning to use MQ-CPH to put in really heavy load and at my company were using SSL for all channel connections so we need to be able to do performancetestings using SSL 

Do you have an example of the parameters needed to get all to work using SSL ?

Best Regards Mats Lundblad , mats.lundblad@seb.se

**Comment by stmassey** [comment]
The MQ client will look in default places for the Keystore, or will use environment variables or qm.ini settings to locate in a alternative location. There is no configuration on mq-cph to define this. The default path for the Keystore is $MQ_INSTALLATION_PATH/ssl

**Comment by sm5wzg** [comment]
Hi thanks for a very quick answer it works fine now, also tried to use MQSSLKEYR environment varaible to point to my Keystore and all works very fine business 

Thanks from Sweden /Mats
