### ISSUE TITLE
Receiver module not working?

### ISSUE THREAD

**Issue by ofisse** [ibm-messaging/mq-cph#2]
The Receiver module appears to be not working. Every invocation of the module reports an unknown argument [cv]:

_**Command line: cph -tc Receiver -nt 10 -jb TEST -jt mqb -d TEST -db 1 -pp -tx
controlThread START
Invalid parameter: Unknown argument [cv]
Invalid parameter: (cv) Cannot retrieve data conversion option.
The current configuration is not valid. Use -h to see available options.**_

Adding -cv true or false, does not appear to work either:

_**Command line: cph -tc Receiver -nt 10 -jb TEST -jt mqb -d TEST -db 1 -pp -tx -cv false

Invalid parameter: Parameter [cv] is not known/valid in this configuration
controlThread START
DLL mqm.dll loaded ok
The current configuration is not valid. Use -h to see available options.**_

**Comment by pharrishur** [comment]
Apologies for the delay in replying. The -cv parm was added relatively recently, and is dependent on  the change that was made to MQOpts.properties as part of its implementation, so you must have the up-to-date version of that on your path. You'll see the cv entries in that props file that are required. If those are missing you'll get the error you describe.  If the file is missing altogether then  "ERROR couldn't open properties file: MQOpts.properties" is issued, so if you think your properties file is up-to-date, then rename it and see if you get that error.

**Comment by ofisse** [comment]
That was my problem, I failed to use the latest version of the property files. Everything is working as expected now, you can close this issue. Thank you..

**Comment by pharrishur** [comment]
np, glad it's working for you now.
