### ISSUE TITLE
need to increase message rate in MQ performance testing | RDQM

### ISSUE THREAD

**Issue by gp-sharma** [ibm-messaging/mq-cph#3]
reference:
[https://github.com/ot4i/perf-harness/issues/9](url)

@stmassey @pharrishur 

Q) We have requirement of increasing the message rate, how it can be achieved?

We tried multiple use cases using multiple threads, multiple flags(nt, db, dx, dn) but we are receiving the same message rate.

requester:
totalIterations=193,totalSeconds=65.92,avgRate=2.93

responder1:
totalIterations=110,totalSeconds=69.36,avgRate=1.59

responder2:
totalIterations=93,totalSeconds=67.54,avgRate=1.38

./cph -tc Requester -nt 5 -jb RDQMDRHAQM2 -jh 10.x.x.x -jp 1416 -jc SYSTEM.DEF.SVRCONN -iq INPUTQ -oq OUTPUTQ -dx 5 -dn 1 -db 1 -jt mqc -pp -tx -ms 4194304 

./cph -tc Responder -nt 5 -jb RDQMDRHAQM2  -jh 10.x.x.x -jp 1416 -jc SYSTEM.DEF.SVRCONN -iq INPUTQ -oq OUTPUTQ -dx 5 -dn 1 -db 1 -jt mqc -pp -tx

we tried with dx and dn flags as well still the message rate is same.

where below is utlization result during test run -

Disk IO - is 16%
CPU is 22% where 2 CPU are allocated
Network utlization is 7GB
Memory - 35%, where 8GB memory allocated.
latency 1.27 ms between client and MQ server

VM is based in Azure with two disk 1) premium SSD of 64 GB, 2) DRBD pool of 128 GB where MQ FS is hosted.

Queue manager is in RDQM.
 
MQ version:
Name:        IBM MQ
Version:     9.2.1.0
Level:       p921-L201112.1
BuildType:   IKAP - (Production)
Platform:    IBM MQ for Linux (x86-64 platform)
Mode:        64-bit
O/S:         Linux 4.18.0-193.14.3.el8_2.x86_64
O/S Details: Red Hat Enterprise Linux 8.2 (Ootpa)
InstName:    Installation1
InstDesc:
Primary:     Yes
InstPath:    /opt/mqm
DataPath:    /var/mqm
MaxCmdLevel: 921
LicenseType: Production

[@aks3333]

**Comment by stmassey** [comment]
To understand if you are seeing any scaling at all, its worth keeping the responders fixed at say 10 threads, and increasing just the requesters to 1,2,4,8,10 threads. 

Before testing RDQM, I would start with NonPersistent messaging to a single QM, then Persistent to that single QM before introducing RDQM.

What are your throughput requirements?

What is your log configuration?

Do you have fastpath enabled?

We have a dockerized test harness that you could use: 
https://github.com/ibm-messaging/cphtestp

and if you want to understand the limits of your Azure FS you can use: 
https://github.com/ibm-messaging/mqldt-c

**Comment by pharrishur** [comment]
I concur with what Sam has said. 
For ease of use you might want to specify '-to -1 -rl 0' on the responder which will make it wait indefinately for messages to appear on the input queue(s) and will not end after the default run length (rl) of 60 seconds. You can also specify -ss 2 (e.g.) to get rate stats every 2 seconds.
I've run some quick tests here and for 5 threads/queues I got 150/sec over a 40Gb link and 12/sec over a 1GB link (persistent messages). That's with my machine, network and filesystems however. The numbers you're seeing are almost certainly reflecting the limitations of your own environment.
Review the performance reports and best practises documents in this repository to make sure you have the basic tuning applied to your queue manager (in particular, you should have fastpath channels enabled and probably set the queue buffers higher for these large messages).
Once you've tuned and re-tested you should try to narrow down where the bottleneck is. As Sam says, try running with non-persistent messages (remove the -pp & -tx parms). If the rates remain the same then the network bandwidth is likely to be the issue. If your non-persistent message rates are much higher, check the performance of the filesystem hosting the MQ recovery log.

**Comment by pharrishur** [comment]
If I restrict my persistent test here to 3/sec then MQ is writing about 25.5MB/sec to the recovery log, with a write size of 1.5MB. You can check if your recovery log filesystem is capable of more than that using the MQLDT tool mentioned above. The write size will depend on a number of factors including write response time. You can check what your own values are using amqsrua. E.g.
/opt/mqm/samp/bin/amqsrua -m RDQMDRHAQM2 -c DISK -t Log

**Comment by gp-sharma** [comment]
What are your throughput requirements?
30000 msgs/sec for non-persistent for 1 MB msg size(for now we are getting 90 msges/sec )
9000 msgs/sec for persistent for 1 MB msg size(for now we are getting 26 msges/sec )

What is your log configuration?
Log:
   LogPrimaryFiles=25
   LogSecondaryFiles=10
   LogFilePages=51200
   LogType=CIRCULAR
   LogBufferPages=4096
   LogPath=/var/mqm/vols/rdqmdrhaqm2/log/rdqmdrhaqm2/
   LogWriteIntegrity=TripleWrite
TuningParameters:
  DefaultQBufferSize=104857600
  DefaultPQBufferSize=104857600


Do you have fastpath enabled?
No. fastpath is not enabled yet. Do we need to set it up if we are using default system listeners ?

output for /opt/mqm/samp/bin/amqsrua -m RDQMDRHAQM2 -c DISK -t Log is:
Publication received PutDate:20210112 PutTime:14491232 Interval:10.000 seconds
Log - bytes in use 5242880000
Log - bytes max 7340032000
Log file system - bytes in use 5353828352
Log file system - bytes max 52571103232
Log - physical bytes written 0
Log - logical bytes written 0
Log - write latency 64469 uSec
Log - write size 1857238
Log - current primary space in use 4.48%
Log - workload primary space utilization 19.48%

we have used IBM standard for RDQM configuration. If any commands that you can share those you have tested in your box with all the required flags that would be appreciated.

@stmassey we have performed non persistent/persistent testing  operation for single QM, the rate remains the same.

**could we connect over the call to discuss?**

**Comment by stmassey** [comment]
Im not sure you going to find any messaging solution that will fulfil those requirements. Youre requesting 9GB/sec which needs to be persisted to disk (in more than one place in the case of RDQM). You really need to understand the capabilities of the environment you are running in. (MQLDT may help here). From the averaged figures above from the QM, your IO subsystem latency is ~60ms for a 2MB write size, so will be limited to ~32MB/sec. A factor of 30 from your requirements. 

30,000Msgs at 1MB for NP messaging requires 30GB or 240Gb of Networking capability, thus you would need to scale this workload across several QM with high capacity networking capability.

Enabling FASTPATH at the QM will optimize processing at the QM, but I think you probably need to discuss your sizing requirements with your IBM client representative. This repo is for support for the CPH tooling and there is a limit to what further advice we can provide.

**Comment by pharrishur** [comment]
Closing this issue as it doesn't relate the the mq-cph tool specifically.
