### ISSUE TITLE
Need to support platform differences (specifically z/OS)

### ISSUE THREAD

**Issue by tonysharkey** [ibm-messaging/mq-cph#6]
When using CPH on Linux to put messages to z/OS QM, there is no way to put a message out-of-syncpoint.

MQIOpts.cpp allows:
* syncpoint to be specified (-tx true)

However the alternative (-tx false) does not set *_NO_SYNCPOINT - instead it relies on the QM's default.

Unlike distributed, the z/OS QM default is have messages put/gotten in syncpoint.
It would be helpful to be able to specify *_NO_SYNCPOINT in order to run out-of-sync puts/gets against a z/OS QM.

Similarly if a queue is defined as DEFPSIST(YES), there is no option to put non-persistent messages.
* persistence to be specified (-pp true) - but -pp false does nothing - picking up the queue option - it would be helpful to be able to determine the persistence explicitly.

**Comment by stmassey** [comment]
Recent updates have added new parms to support explicit overriding of NP and Non Tx modes. See -txz and -ppn parms. cph.pdf document updated.
