### ISSUE TITLE
How to set MQMD message format in MQCPH

### ISSUE THREAD

**Issue by TestUser-tech246** [ibm-messaging/mq-cph#7]
We have a requirement to send the message format to backend service as 'MQIMS' but by default MQCPH is sending as 'MQSTR', could you please help to let us know if there any parameter we can use to set this.
Command used: cph -tc Sender -jb QM -jt mqb -d Queue -ms 100 -mg 1

**Comment by stmassey** [comment]
Ive just added support for `-mqm <format>` which will set the format into the MQMD. Ive done limited testing, so please feedback any comments.

**Comment by TestUser-tech246** [comment]
Thank you for response. I have tried below command 
cph -tc Sender -jb QM -jt mqb -d Queue -ms 100 -mg 1 -mfm MQIMS 
And now the header on the queue showing as 'MQIMS'.
Do we also have any option to include MQIIH header information like Code character set Id and Encoding, as these are few important options to set and are setting as default. But in our test this information also should be changed.

**Comment by stmassey** [comment]
It was simple to add and test the MQMD format field. Adding ccsid and encoding support (and testing it), would be less straight forward. I suggest forking the repo and customizing it for your specific scenario is probably the best option here.

**Comment by TestUser-tech246** [comment]
Thank you for your response, we tried analyzing the files but couldn't be able to figure out in which file the MQIMS headers are required to be added. Could you please suggest us in which files these changes are to be placed.

**Comment by stmassey** [comment]
Im not familar with z/OS or IMS headers, but likely you will need to modify the creation of the message in MQIOther.cpp
